/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnniversairesRouteImport } from './routes/anniversaires'
import { Route as CarnetRouteImport } from './routes/carnet'
import { Route as DatavizRouteImport } from './routes/dataviz'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as FuitesRouteImport } from './routes/fuites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NominationsRouteImport } from './routes/nominations'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PromessesRouteImport } from './routes/promesses'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SignauxRouteImport } from './routes/signaux'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnniversairesRoute = AnniversairesRouteImport.update({
  id: '/anniversaires',
  path: '/anniversaires',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetRoute = CarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const DatavizRoute = DatavizRouteImport.update({
  id: '/dataviz',
  path: '/dataviz',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const FuitesRoute = FuitesRouteImport.update({
  id: '/fuites',
  path: '/fuites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NominationsRoute = NominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PromessesRoute = PromessesRouteImport.update({
  id: '/promesses',
  path: '/promesses',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SignauxRoute = SignauxRouteImport.update({
  id: '/signaux',
  path: '/signaux',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/equipe': typeof EquipeRoute
  '/espace': typeof EspaceRoute
  '/fuites': typeof FuitesRoute
  '/login': typeof LoginRoute
  '/nominations': typeof NominationsRoute
  '/notes': typeof NotesRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/equipe': typeof EquipeRoute
  '/espace': typeof EspaceRoute
  '/fuites': typeof FuitesRoute
  '/login': typeof LoginRoute
  '/nominations': typeof NominationsRoute
  '/notes': typeof NotesRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/equipe': typeof EquipeRoute
  '/espace': typeof EspaceRoute
  '/fuites': typeof FuitesRoute
  '/login': typeof LoginRoute
  '/nominations': typeof NominationsRoute
  '/notes': typeof NotesRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/equipe'
    | '/espace'
    | '/fuites'
    | '/login'
    | '/nominations'
    | '/notes'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/equipe'
    | '/espace'
    | '/fuites'
    | '/login'
    | '/nominations'
    | '/notes'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/equipe'
    | '/espace'
    | '/fuites'
    | '/login'
    | '/nominations'
    | '/notes'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnniversairesRoute: typeof AnniversairesRoute
  CarnetRoute: typeof CarnetRoute
  DatavizRoute: typeof DatavizRoute
  EquipeRoute: typeof EquipeRoute
  EspaceRoute: typeof EspaceRoute
  FuitesRoute: typeof FuitesRoute
  LoginRoute: typeof LoginRoute
  NominationsRoute: typeof NominationsRoute
  NotesRoute: typeof NotesRoute
  PromessesRoute: typeof PromessesRoute
  PublicationsRoute: typeof PublicationsRoute
  SignauxRoute: typeof SignauxRoute
  SourcesRoute: typeof SourcesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anniversaires': {
      id: '/anniversaires'
      path: '/anniversaires'
      fullPath: '/anniversaires'
      preLoaderRoute: typeof AnniversairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet': {
      id: '/carnet'
      path: '/carnet'
      fullPath: '/carnet'
      preLoaderRoute: typeof CarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataviz': {
      id: '/dataviz'
      path: '/dataviz'
      fullPath: '/dataviz'
      preLoaderRoute: typeof DatavizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuites': {
      id: '/fuites'
      path: '/fuites'
      fullPath: '/fuites'
      preLoaderRoute: typeof FuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominations': {
      id: '/nominations'
      path: '/nominations'
      fullPath: '/nominations'
      preLoaderRoute: typeof NominationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promesses': {
      id: '/promesses'
      path: '/promesses'
      fullPath: '/promesses'
      preLoaderRoute: typeof PromessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaux': {
      id: '/signaux'
      path: '/signaux'
      fullPath: '/signaux'
      preLoaderRoute: typeof SignauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnniversairesRoute: AnniversairesRoute,
  CarnetRoute: CarnetRoute,
  DatavizRoute: DatavizRoute,
  EquipeRoute: EquipeRoute,
  EspaceRoute: EspaceRoute,
  FuitesRoute: FuitesRoute,
  LoginRoute: LoginRoute,
  NominationsRoute: NominationsRoute,
  NotesRoute: NotesRoute,
  PromessesRoute: PromessesRoute,
  PublicationsRoute: PublicationsRoute,
  SignauxRoute: SignauxRoute,
  SourcesRoute: SourcesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
