/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnniversairesRouteImport } from './routes/anniversaires'
import { Route as CarnetRouteImport } from './routes/carnet'
import { Route as DatavizRouteImport } from './routes/dataviz'
import { Route as NominationsRouteImport } from './routes/nominations'
import { Route as PromessesRouteImport } from './routes/promesses'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SignauxRouteImport } from './routes/signaux'
import { Route as SourcesRouteImport } from './routes/sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnniversairesRoute = AnniversairesRouteImport.update({
  id: '/anniversaires',
  path: '/anniversaires',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetRoute = CarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const DatavizRoute = DatavizRouteImport.update({
  id: '/dataviz',
  path: '/dataviz',
  getParentRoute: () => rootRouteImport,
} as any)
const NominationsRoute = NominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => rootRouteImport,
} as any)
const PromessesRoute = PromessesRouteImport.update({
  id: '/promesses',
  path: '/promesses',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SignauxRoute = SignauxRouteImport.update({
  id: '/signaux',
  path: '/signaux',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/nominations': typeof NominationsRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/nominations': typeof NominationsRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anniversaires': typeof AnniversairesRoute
  '/carnet': typeof CarnetRoute
  '/dataviz': typeof DatavizRoute
  '/nominations': typeof NominationsRoute
  '/promesses': typeof PromessesRoute
  '/publications': typeof PublicationsRoute
  '/signaux': typeof SignauxRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/nominations'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/nominations'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/anniversaires'
    | '/carnet'
    | '/dataviz'
    | '/nominations'
    | '/promesses'
    | '/publications'
    | '/signaux'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnniversairesRoute: typeof AnniversairesRoute
  CarnetRoute: typeof CarnetRoute
  DatavizRoute: typeof DatavizRoute
  NominationsRoute: typeof NominationsRoute
  PromessesRoute: typeof PromessesRoute
  PublicationsRoute: typeof PublicationsRoute
  SignauxRoute: typeof SignauxRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anniversaires': {
      id: '/anniversaires'
      path: '/anniversaires'
      fullPath: '/anniversaires'
      preLoaderRoute: typeof AnniversairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet': {
      id: '/carnet'
      path: '/carnet'
      fullPath: '/carnet'
      preLoaderRoute: typeof CarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataviz': {
      id: '/dataviz'
      path: '/dataviz'
      fullPath: '/dataviz'
      preLoaderRoute: typeof DatavizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominations': {
      id: '/nominations'
      path: '/nominations'
      fullPath: '/nominations'
      preLoaderRoute: typeof NominationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promesses': {
      id: '/promesses'
      path: '/promesses'
      fullPath: '/promesses'
      preLoaderRoute: typeof PromessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaux': {
      id: '/signaux'
      path: '/signaux'
      fullPath: '/signaux'
      preLoaderRoute: typeof SignauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnniversairesRoute: AnniversairesRoute,
  CarnetRoute: CarnetRoute,
  DatavizRoute: DatavizRoute,
  NominationsRoute: NominationsRoute,
  PromessesRoute: PromessesRoute,
  PublicationsRoute: PublicationsRoute,
  SignauxRoute: SignauxRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
